import { z } from "zod";

export const speakingCategorySchema = z.enum(["mock", "part-1", "part-2", "part-3"]);

export const speakingQuestionSchema = z.object({
  // `id` is accepted from the existing admin editor but database IDs are
  // generated by Prisma and returned in learner-facing test content.
  id: z.string().min(1).optional(),
  text: z.string().trim().min(1, "Question text is required").max(5_000),
});

export const speakingPart1Schema = z.object({
  questions: z.array(speakingQuestionSchema).max(30),
  durationMinutes: z.number().int().min(1).max(20).default(5),
});

export const speakingPart2Schema = z.object({
  cueCardTitle: z.string().trim().max(500),
  cueCardDescription: z.string().trim().max(10_000),
  bulletPoints: z.array(z.string().trim().max(1_000)).max(8),
  closingQuestion: z.string().trim().max(5_000).default(""),
  preparationMinutes: z.number().int().min(1).max(5).default(1),
  speakingMinutes: z.number().int().min(1).max(10).default(2),
});

export const speakingPart3Schema = z.object({
  topic: z.string().trim().max(500),
  questions: z.array(speakingQuestionSchema).max(30),
  durationMinutes: z.number().int().min(1).max(20).default(5),
});

export const createSpeakingTestSchema = z.object({
  title: z.string().trim().min(3).max(300),
  category: speakingCategorySchema,
  part1: speakingPart1Schema,
  part2: speakingPart2Schema,
  part3: speakingPart3Schema,
});

export const updateSpeakingTestSchema = createSpeakingTestSchema.partial();

const speakingRecordingSchema = z
  .object({
    // `audioUrl` preserves the current recorder payload. Production clients
    // should use a durable object-storage URL or `audioStorageKey`, not a
    // browser-only blob URL.
    audioUrl: z.string().min(1).max(20_000).optional(),
    audioStorageKey: z.string().min(1).max(1_000).optional(),
    durationSeconds: z.number().int().min(1).max(10_800),
    transcript: z.string().trim().max(100_000).optional(),
  })
  .refine((recording) => recording.audioUrl || recording.audioStorageKey, {
    message: "A recording needs an audioUrl or audioStorageKey.",
  });

export const speakingRecordingsSchema = z
  .record(z.string().min(1).max(500), speakingRecordingSchema)
  .refine((recordings) => Object.keys(recordings).length <= 100, {
    message: "Too many recordings supplied.",
  });

export const saveSpeakingRecordingsSchema = z.object({
  recordings: speakingRecordingsSchema,
});

export const submitSpeakingAttemptSchema = z.object({
  // Allows the frontend to submit recordings that have not yet been autosaved.
  recordings: speakingRecordingsSchema.optional(),
});

const questionMetadataSchema = z.object({
  questionIds: z.array(z.string().trim().min(1).max(500)).max(30).optional(),
  topic: z.string().trim().max(500).optional(),
  prompt: z.string().trim().max(10_000).optional(),
  expectedDurationSeconds: z.number().int().min(1).max(10_800).optional(),
  questionCount: z.number().int().min(1).max(30).optional(),
});

const speakingEvaluationRecordingSchema = z
  .object({
    responseKey: z.string().trim().min(1).max(500),
    audioUrl: z.string().trim().min(1).max(20_000).optional(),
    audioStorageKey: z.string().trim().min(1).max(1_000).optional(),
    mimeType: z.string().trim().min(1).max(255).optional(),
    durationSeconds: z.number().int().min(1).max(10_800),
    // This is permitted only for trusted upstream STT workflows. When absent,
    // the configured speech-to-text provider receives the audio reference.
    transcript: z.string().trim().min(1).max(100_000).optional(),
    questionMetadata: questionMetadataSchema.default({}),
  })
  .refine((recording) => recording.audioUrl || recording.audioStorageKey, {
    message: "A recording needs an audioUrl or audioStorageKey.",
  });

const speakingEvaluationPartSchema = z.object({
  partNumber: z.union([z.literal(1), z.literal(2), z.literal(3)]),
  questionMetadata: questionMetadataSchema.default({}),
  recordings: z.array(speakingEvaluationRecordingSchema).min(1).max(30),
});

/**
 * An evaluation submission can represent a standalone IELTS part or all
 * three parts in one mock test. Audio itself should already be stored behind
 * a durable URL/key; storage upload is intentionally separate from scoring.
 */
export const createSpeakingSubmissionSchema = z
  .object({
    mode: z.enum(["part", "mock"]),
    testId: z.string().trim().min(1).max(500).optional(),
    attemptId: z.string().trim().min(1).max(500).optional(),
    parts: z.array(speakingEvaluationPartSchema).min(1).max(3),
  })
  .superRefine((submission, ctx) => {
    const partNumbers = submission.parts.map((part) => part.partNumber);
    if (new Set(partNumbers).size !== partNumbers.length) {
      ctx.addIssue({ code: "custom", path: ["parts"], message: "Each speaking part can be submitted only once." });
    }
    if (submission.mode === "part" && submission.parts.length !== 1) {
      ctx.addIssue({ code: "custom", path: ["parts"], message: "A part submission must contain exactly one part." });
    }
    if (
      submission.mode === "mock" &&
      (submission.parts.length !== 3 || !([1, 2, 3] as const).every((part) => partNumbers.includes(part)))
    ) {
      ctx.addIssue({ code: "custom", path: ["parts"], message: "A mock submission must contain Parts 1, 2, and 3." });
    }
    for (const [partIndex, part] of submission.parts.entries()) {
      const responseKeys = part.recordings.map((recording) => recording.responseKey);
      if (new Set(responseKeys).size !== responseKeys.length) {
        ctx.addIssue({
          code: "custom",
          path: ["parts", partIndex, "recordings"],
          message: "Response keys must be unique within a part.",
        });
      }
    }
  });

export const speakingSubmissionParamsSchema = z.object({
  id: z.string().trim().min(1).max(500),
});

export const publishedSpeakingTestsQuerySchema = z.object({
  category: speakingCategorySchema.optional(),
  page: z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(50).default(12),
});

export type SpeakingCategory = z.infer<typeof speakingCategorySchema>;
export type CreateSpeakingTestInput = z.infer<typeof createSpeakingTestSchema>;
export type UpdateSpeakingTestInput = z.infer<typeof updateSpeakingTestSchema>;
export type SpeakingRecordings = z.infer<typeof speakingRecordingsSchema>;
export type SaveSpeakingRecordingsInput = z.infer<typeof saveSpeakingRecordingsSchema>;
export type SubmitSpeakingAttemptInput = z.infer<typeof submitSpeakingAttemptSchema>;
export type CreateSpeakingSubmissionInput = z.infer<typeof createSpeakingSubmissionSchema>;
